# Generated by Django 4.1.2 on 2022-11-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
